package radio.ks3ckc.sstvaf.sstv.digital

/**
 * Arithmetic over the finite field GF(2^8) used by the digital-SSTV
 * Reed-Solomon code ([ReedSolomon]).
 *
 * The field is generated by the primitive polynomial x^8 + x^4 + x^3 + x^2 + 1
 * (`0x11d`) with generator element `2` — the same field convention used by the
 * DRM/DVB and QR-code Reed-Solomon codes, so goldens are easy to cross-check.
 *
 * Elements are bytes carried as `Int` in `[0, 255]`. Addition/subtraction are
 * XOR; multiplication/division go through the log/antilog tables built once in
 * the initializer.
 */
internal object Gf256 {
    const val PRIMITIVE = 0x11d
    const val GENERATOR = 2

    /** Antilog table, doubled to `[0, 510]` so `exp[a + b]` never wraps. */
    private val exp = IntArray(512)

    /** Log table over `[1, 255]`; `log[0]` is undefined and left 0. */
    private val log = IntArray(256)

    init {
        var x = 1
        for (i in 0 until 255) {
            exp[i] = x
            log[x] = i
            x = x shl 1
            if (x and 0x100 != 0) x = x xor PRIMITIVE
        }
        for (i in 255 until 512) exp[i] = exp[i - 255]
    }

    fun mul(a: Int, b: Int): Int = if (a == 0 || b == 0) 0 else exp[log[a] + log[b]]

    fun div(a: Int, b: Int): Int {
        require(b != 0) { "GF(256) division by zero" }
        return if (a == 0) 0 else exp[(log[a] + 255 - log[b]) % 255]
    }

    /** `a^n` in the field (n may be any non-negative int). */
    fun pow(a: Int, n: Int): Int = if (a == 0) 0 else exp[(log[a] * n) % 255]

    /** Multiplicative inverse of a non-zero element. */
    fun inv(a: Int): Int {
        require(a != 0) { "GF(256) inverse of zero" }
        return exp[255 - log[a]]
    }

    /** `generator^i` — the roots used to build the RS generator polynomial. */
    fun expGen(i: Int): Int = pow(GENERATOR, i)
}
